

SELECT 
    C.NOME AS Nome_Cliente,
    F.TITULO AS Titulo_Filme,
    L.DATA_LOC AS Data_Locacao,
    LF.DATA_DEVOL AS Data_Devolucao
FROM 
    CLIENTE C
JOIN 
    LOCACAO L ON C.COD_CLI = L.COD_CLI
JOIN 
    LOCACAO_FILME LF ON L.COD_LOC = LF.COD_LOC
JOIN 
    FILMES F ON LF.COD_FILME = F.COD_FILME
WHERE 
    C.COD_CLI = 1;



SELECT 
    CLIENTE.COD_CLI AS CODIGO_CLIENTE,
    CLIENTE.CPF AS CPF_CLIENTE,
    CLIENTE.NOME AS NOME_CLIENTE,
    CLIENTE.TELEFONE AS TELEFONE_CLIENTE,
    DEPENDENTE.COD_DEP AS CODIGO_DEPENDENTE,
    DEPENDENTE.PARENTESCO AS PARENTESCO
FROM 
    CLIENTE
JOIN 
    DEPENDENTE ON CLIENTE.COD_CLI = DEPENDENTE.COD_CLI
ORDER BY 
    CLIENTE.COD_CLI;


SELECT 
    F.COD_FILME, 
    F.TITULO_ORIGINAL, 
    F.TITULO, 
    G.NOME AS GENERO
FROM 
    FILMES F
JOIN 
    GENERO G ON F.COD_GEN = G.COD_GEN
WHERE 
    G.NOME = 'Ação';




SELECT CLIENTE.COD_CLI, CLIENTE.CPF, CLIENTE.NOME, CLIENTE.TELEFONE, PROFISSAO.NOME AS PROFISSAO
FROM CLIENTE
JOIN PROFISSAO ON CLIENTE.COD_PROF = PROFISSAO.COD_PROF
WHERE PROFISSAO.NOME = 'Médico';



SELECT F.TITULO_ORIGINAL, F.TITULO, F.QUANTIDADE, C.NOME AS CATEGORIA
FROM FILMES F
JOIN CATEGORIA C ON F.COD_CAT = C.COD_CAT
WHERE F.QUANTIDADE > 5 AND C.NOME = 'Infantil';


SELECT ATOR.NOME
FROM FILMES
JOIN FILME_ATOR ON FILMES.COD_FILME = FILME_ATOR.COD_FILME
JOIN ATOR ON FILME_ATOR.COD_ATOR = ATOR.COD_ATOR
WHERE FILMES.TITULO = 'A Origem';


SELECT 
    CLIENTE.NOME,
    ENDERECO.LOGRADOURO,
    ENDERECO.TIPO_LOG,
    ENDERECO.COMPLEMENTO,
    ENDERECO.CIDADE,
    ENDERECO.UF,
    ENDERECO.CEP,
    ENDERECO.NUMERO,
    ENDERECO.BAIRRO
FROM CLIENTE
JOIN CLI_ENDERECO ON CLIENTE.COD_CLI = CLI_ENDERECO.COD_CLI
JOIN ENDERECO ON CLI_ENDERECO.COD_END = ENDERECO.COD_END
WHERE CLIENTE.COD_CLI = 2;


SELECT 
    F.TITULO_ORIGINAL AS "Título Original", 
    F.TITULO AS "Título", 
    G.NOME AS "Gênero", 
    C.NOME AS "Categoria"
FROM 
    FILMES F
JOIN 
    GENERO G ON F.COD_GEN = G.COD_GEN
JOIN 
    CATEGORIA C ON F.COD_CAT = C.COD_CAT;



SELECT 
    C.NOME AS Cliente,
    L.DATA_LOC AS Data_Locacao
FROM 
    CLIENTE C
JOIN 
    LOCACAO L ON C.COD_CLI = L.COD_CLI
JOIN 
    LOCACAO_FILME LF ON L.COD_LOC = LF.COD_LOC
WHERE 
    LF.COD_FILME = 1;



SELECT 
    CLIENTE.COD_CLI,
    CLIENTE.NOME,
    LOCACAO.MULTA
FROM 
    CLIENTE
JOIN 
    LOCACAO ON CLIENTE.COD_CLI = LOCACAO.COD_CLI
WHERE 
    LOCACAO.MULTA > 10.00;


SELECT
    LOCACAO.COD_LOC,
    LOCACAO.DATA_LOC,
    LOCACAO.DESCONTO,
    LOCACAO.MULTA,
    LOCACAO.SUB_TOTAL,
    CLIENTE.NOME AS NOME_CLIENTE,
    CLIENTE.CPF,
    CLIENTE.TELEFONE,
    PROFISSAO.NOME AS PROFISSAO_CLIENTE
FROM
    LOCACAO
JOIN
    CLIENTE ON LOCACAO.COD_CLI = CLIENTE.COD_CLI
JOIN
    PROFISSAO ON CLIENTE.COD_PROF = PROFISSAO.COD_PROF
WHERE
    YEAR(LOCACAO.DATA_LOC) = 2023;



SELECT
    CLIENTE.COD_CLI,
    CLIENTE.NOME AS NOME_CLIENTE,
    COUNT(LOCACAO_FILME.COD_FILME) AS QUANTIDADE_TOTAL
FROM
    CLIENTE
LEFT JOIN
    LOCACAO ON CLIENTE.COD_CLI = LOCACAO.COD_CLI
LEFT JOIN
    LOCACAO_FILME ON LOCACAO.COD_LOC = LOCACAO_FILME.COD_LOC
GROUP BY
    CLIENTE.COD_CLI, CLIENTE.NOME
ORDER BY
    CLIENTE.COD_CLI;



SELECT
    CLI.COD_CLI,
    CLI.NOME AS NOME_CLIENTE,
    F.TITULO AS TITULO_FILME,
    LF.DATA_LOC
FROM
    CLIENTE CLI
INNER JOIN
    LOCACAO L ON CLI.COD_CLI = L.COD_CLI
INNER JOIN
    LOCACAO_FILME LF ON L.COD_LOC = LF.COD_LOC
INNER JOIN
    FILMES F ON LF.COD_FILME = F.COD_FILME
ORDER BY
    LF.DATA_LOC;



SELECT
    CLI.COD_CLI,
    CLI.NOME AS NOME_CLIENTE,
    ENDER.CIDADE,
    F.TITULO AS TITULO_FILME,
    CAT.NOME AS CATEGORIA_FILME
FROM
    CLIENTE CLI
INNER JOIN
    CLI_ENDERECO CE ON CLI.COD_CLI = CE.COD_CLI
INNER JOIN
    ENDERECO ENDER ON CE.COD_END = ENDER.COD_END
INNER JOIN
    LOCACAO L ON CLI.COD_CLI = L.COD_CLI
INNER JOIN
    LOCACAO_FILME LF ON L.COD_LOC = LF.COD_LOC
INNER JOIN
    FILMES F ON LF.COD_FILME = F.COD_FILME
INNER JOIN
    CATEGORIA CAT ON F.COD_CAT = CAT.COD_CAT
WHERE
    ENDER.CIDADE = 'São Paulo'
    AND CAT.COD_CAT = 2;



SELECT
    A.NOME AS NOME_ATOR,
    COUNT(FA.COD_FILME) AS NUMERO_FILMES
FROM
    ATOR A
INNER JOIN
    FILME_ATOR FA ON A.COD_ATOR = FA.COD_ATOR
GROUP BY
    A.NOME
HAVING
    COUNT(FA.COD_FILME) >= 5
ORDER BY
    NUMERO_FILMES DESC;



SELECT
    C.NOME AS CATEGORIA,
    G.NOME AS GENERO,
    COUNT(LF.COD_FILME) AS QUANTIDADE_TOTAL
FROM
    LOCACAO_FILME LF
INNER JOIN
    FILMES F ON LF.COD_FILME = F.COD_FILME
INNER JOIN
    CATEGORIA C ON F.COD_CAT = C.COD_CAT
INNER JOIN
    GENERO G ON F.COD_GEN = G.COD_GEN
GROUP BY
    C.NOME, G.NOME
HAVING
    COUNT(LF.COD_FILME) > 5
ORDER BY
    QUANTIDADE_TOTAL DESC;
